name: Godot Export
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Godot Export
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_export_templates.tpz
          archive_output: true
          cache: true
          relative_export_path: ./
          verbose: true
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: /home/runner/work/LittleRage/LittleRage/Windows.zip
          retention-days: 5
      - name: Upload Linux x86_64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-x86_64-build
          path: /home/runner/work/LittleRage/LittleRage/LinuxX86_64.zip
          retention-days: 5
      - name: Upload Linux Arm64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64-build
          path: /home/runner/work/LittleRage/LittleRage/LinuxArm64.zip
          retention-days: 5
      - name: Upload MacOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: /home/runner/work/LittleRage/LittleRage/macOS.zip
          retention-days: 5
