name: Build Little Rage

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [LinuxX86_64, LinuxArm64, WindowsX86_64, WindowsArm64, Web, macOS]
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          lfs: true
      - name: Build
        id: build
        uses: krynv/build-godot-action@v1.0.0
        with:
          name: little-rage
          preset: ${{ matrix.platform }}
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Little Rage - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
